name: Auto check code

on:
  push:
    branches:
      - main
      - master
    paths:
      - lib/**.dart
      - bin/**.dart
      - .github/workflows/auto-pr-code.yaml

jobs:
  check-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name: Check code
    steps:
      - uses: actions/checkout@v4
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
      - name: Generate index dart
        run: |
          flutter pub global activate index_generator
          flutter pub global run index_generator:index_generator
      - name: Format code
        run: |
          dart format lib/
          dart format bin/
      - name: Fix code
        run: dart fix --apply
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Auto format code"
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          title: "chore: Auto format code"
          body: "chore: Auto format code"
          signoff: true
          branch: "auto-format"
          branch-suffix: "timestamp"
          delete-branch: true
          labels: "auto-merge"
